#!/usr/bin/env node
import { runDirect } from "./runtime/cli.mts";
/*
 * Records a version-log entry for this bundle. Bumps VERSION (semver) and prepends a
 * dated section to CHANGELOG.md. Run this whenever a structural improvement lands —
 * a new/changed skill, agent, rule, script, template, or hook. See
 * .claude/skills/changelog/SKILL.md for when/how to invoke it.
 *
 * Write mode:  node ai-framework/scripts/changelog.mts --bump patch|minor|major
 *                --category Added|Changed|Fixed|Removed --summary "..."
 *                [--detail "..." ...] [--files "path1,path2"] [--json]
 * Read mode:   node ai-framework/scripts/changelog.mts --check [--json]
 *
 * Imports no node:* module at runtime: every fs/path/process/clock effect goes through the injected
 * RuntimeDeps. VERSION and CHANGELOG.md are read and written in the working directory.
 */

import type { RuntimeDeps } from "./runtime/types.mts";

export interface EntryParts {
  version: string;
  category: string;
  summary: string;
  details: string[];
  files: string[];
  date: string;
}

export interface LatestEntry {
  version: string;
  date: string;
  category: string;
  bullets: string[];
}

interface Context {
  deps: RuntimeDeps;
  argv: string[];
  json: boolean;
  versionPath: string;
  changelogPath: string;
}

function messageOf(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function codeOf(error: unknown): unknown {
  return typeof error === "object" && error !== null ? (error as { code?: unknown }).code : undefined;
}

function arg(argv: string[], name: string): string | undefined {
  const index = argv.indexOf(`--${name}`);
  if (index === -1) return undefined;
  return argv[index + 1];
}

function allArgs(argv: string[], name: string): Array<string | undefined> {
  const flag = `--${name}`;
  const values: Array<string | undefined> = [];
  argv.forEach((value, index) => {
    if (value === flag) values.push(argv[index + 1]);
  });
  return values;
}

/** Reports a failure the way the CLI always has: JSON on stdout under --json, else `error: ...` on stderr. Returns 1. */
function fail(ctx: Context, message: string): number {
  if (ctx.json) {
    ctx.deps.io.stdout.write(JSON.stringify({ ok: false, error: message }) + "\n");
  } else {
    ctx.deps.io.stderr.write(`error: ${message}\n`);
  }
  return 1;
}

async function readVersion(ctx: Context): Promise<string> {
  try {
    const raw = await ctx.deps.fs.readFile(ctx.versionPath);
    return raw.trim() || "0.0.0";
  } catch (error) {
    if (codeOf(error) === "ENOENT") return "0.0.0";
    throw error;
  }
}

export function bump(version: string, kind: string | undefined): string {
  const match = version.match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) throw new Error(`VERSION is not valid semver: "${version}"`);
  let [, major, minor, patch] = match.map(Number);
  if (kind === "major") { major += 1; minor = 0; patch = 0; }
  else if (kind === "minor") { minor += 1; patch = 0; }
  else if (kind === "patch") { patch += 1; }
  else throw new Error(`--bump must be patch, minor, or major (got "${kind}")`);
  return `${major}.${minor}.${patch}`;
}

async function readChangelog(ctx: Context): Promise<string> {
  try {
    return await ctx.deps.fs.readFile(ctx.changelogPath);
  } catch (error) {
    if (codeOf(error) === "ENOENT") {
      return "# Changelog\n\nAll notable changes to this AI workflow bundle are recorded here, " +
        "newest first.\nGenerated by `ai-framework/scripts/changelog.mts` — do not hand-edit past " +
        "entries.\n";
    }
    throw error;
  }
}

export function buildEntry({ version, category, summary, details, files, date }: EntryParts): string {
  const lines = [`## [${version}] - ${date}`, `### ${category}`, `- ${summary}`];
  for (const detail of details) lines.push(`- ${detail}`);
  if (files.length) lines.push(`\nFiles: ${files.join(", ")}`);
  return lines.join("\n") + "\n";
}

export function insertEntry(existing: string, entry: string): string {
  const marker = "\n## [";
  const firstEntry = existing.indexOf(marker);
  if (firstEntry === -1) {
    const trimmed = existing.replace(/\n+$/, "\n");
    return `${trimmed}\n${entry}`;
  }
  return `${existing.slice(0, firstEntry + 1)}${entry}\n${existing.slice(firstEntry + 1)}`;
}

async function runCheck(ctx: Context): Promise<number> {
  const { io } = ctx.deps;
  const version = await readVersion(ctx);
  const changelog = await readChangelog(ctx);
  const match = changelog.match(/## \[([^\]]+)\] - ([\d-]+)\n### (\w+)\n((?:- .+\n?)+)/);
  const latest: LatestEntry | null = match
    ? { version: match[1], date: match[2], category: match[3], bullets: match[4].trim().split("\n") }
    : null;
  if (ctx.json) {
    io.stdout.write(JSON.stringify({ ok: true, version, latest }) + "\n");
  } else {
    io.stdout.write(`VERSION: ${version}\n`);
    if (latest) {
      io.stdout.write(`Latest entry: [${latest.version}] ${latest.date} (${latest.category})\n`);
      latest.bullets.forEach((bullet) => io.stdout.write(`  ${bullet}\n`));
    } else {
      io.stdout.write("No CHANGELOG.md entries yet.\n");
    }
  }
  return 0;
}

async function runWrite(ctx: Context): Promise<number> {
  const { deps, argv } = ctx;
  const bumpKind = arg(argv, "bump");
  const category = arg(argv, "category");
  const summary = arg(argv, "summary");
  const details = allArgs(argv, "detail").filter((value): value is string => Boolean(value));
  const filesArg = arg(argv, "files");
  const files = filesArg ? filesArg.split(",").map((item) => item.trim()).filter(Boolean) : [];

  if (!bumpKind || !["patch", "minor", "major"].includes(bumpKind)) {
    return fail(ctx, '--bump must be one of "patch", "minor", "major"');
  }
  if (!category || !["Added", "Changed", "Fixed", "Removed"].includes(category)) {
    return fail(ctx, '--category must be one of "Added", "Changed", "Fixed", "Removed"');
  }
  if (!summary) return fail(ctx, "--summary is required (one short line describing the improvement)");

  const current = await readVersion(ctx);
  const next = bump(current, bumpKind);
  const date = new Date(deps.clock.now()).toISOString().slice(0, 10);
  const entry = buildEntry({ version: next, category, summary, details, files, date });
  const existingChangelog = await readChangelog(ctx);
  const updatedChangelog = insertEntry(existingChangelog, entry);

  await deps.fs.writeFile(ctx.versionPath, `${next}\n`);
  await deps.fs.writeFile(ctx.changelogPath, updatedChangelog);

  if (ctx.json) {
    deps.io.stdout.write(JSON.stringify({ ok: true, previousVersion: current, version: next }) + "\n");
  } else {
    deps.io.stdout.write(`VERSION ${current} -> ${next}\n`);
    deps.io.stdout.write(`CHANGELOG.md updated:\n\n${entry}`);
  }
  return 0;
}

/** CLI entry. `argv` excludes the script path. Returns the exit code. */
export async function main(argv: string[], deps: RuntimeDeps): Promise<number> {
  const root = deps.proc.cwd();
  const ctx: Context = {
    deps,
    argv,
    json: argv.includes("--json"),
    versionPath: deps.path.join(root, "VERSION"),
    changelogPath: deps.path.join(root, "CHANGELOG.md"),
  };
  try {
    return argv.includes("--check") ? await runCheck(ctx) : await runWrite(ctx);
  } catch (error) {
    return fail(ctx, messageOf(error));
  }
}

runDirect(import.meta.url, main);
