#!/usr/bin/env node
/*
 * Records a version-log entry for this bundle. Bumps VERSION (semver) and prepends a
 * dated section to CHANGELOG.md. Run this whenever a structural improvement lands —
 * a new/changed skill, agent, rule, script, template, or hook. See
 * .claude/skills/changelog/SKILL.md for when/how to invoke it.
 *
 * Write mode:  node ai-framework/scripts/changelog.js --bump patch|minor|major
 *                --category Added|Changed|Fixed|Removed --summary "..."
 *                [--detail "..." ...] [--files "path1,path2"] [--json]
 * Read mode:   node ai-framework/scripts/changelog.js --check [--json]
 */

const fsp = require("node:fs/promises");
const path = require("node:path");

const root = process.cwd();
const versionPath = path.join(root, "VERSION");
const changelogPath = path.join(root, "CHANGELOG.md");
const json = process.argv.includes("--json");

function arg(name) {
  const flag = `--${name}`;
  const index = process.argv.indexOf(flag);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

function allArgs(name) {
  const flag = `--${name}`;
  const values = [];
  process.argv.forEach((value, index) => {
    if (value === flag) values.push(process.argv[index + 1]);
  });
  return values;
}

function fail(message) {
  if (json) {
    process.stdout.write(JSON.stringify({ ok: false, error: message }) + "\n");
  } else {
    process.stderr.write(`error: ${message}\n`);
  }
  process.exitCode = 1;
}

async function readVersion() {
  try {
    const raw = await fsp.readFile(versionPath, "utf8");
    return raw.trim() || "0.0.0";
  } catch (error) {
    if (error.code === "ENOENT") return "0.0.0";
    throw error;
  }
}

function bump(version, kind) {
  const match = version.match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) throw new Error(`VERSION is not valid semver: "${version}"`);
  let [, major, minor, patch] = match.map(Number);
  if (kind === "major") { major += 1; minor = 0; patch = 0; }
  else if (kind === "minor") { minor += 1; patch = 0; }
  else if (kind === "patch") { patch += 1; }
  else throw new Error(`--bump must be patch, minor, or major (got "${kind}")`);
  return `${major}.${minor}.${patch}`;
}

async function readChangelog() {
  try {
    return await fsp.readFile(changelogPath, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") {
      return "# Changelog\n\nAll notable changes to this AI workflow bundle are recorded here, " +
        "newest first.\nGenerated by `ai-framework/scripts/changelog.js` — do not hand-edit past " +
        "entries.\n";
    }
    throw error;
  }
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function buildEntry({ version, category, summary, details, files }) {
  const lines = [`## [${version}] - ${today()}`, `### ${category}`, `- ${summary}`];
  for (const detail of details) lines.push(`- ${detail}`);
  if (files.length) lines.push(`\nFiles: ${files.join(", ")}`);
  return lines.join("\n") + "\n";
}

function insertEntry(existing, entry) {
  const marker = "\n## [";
  const firstEntry = existing.indexOf(marker);
  if (firstEntry === -1) {
    const trimmed = existing.replace(/\n+$/, "\n");
    return `${trimmed}\n${entry}`;
  }
  return `${existing.slice(0, firstEntry + 1)}${entry}\n${existing.slice(firstEntry + 1)}`;
}

async function runCheck() {
  const version = await readVersion();
  const changelog = await readChangelog();
  const match = changelog.match(/## \[([^\]]+)\] - ([\d-]+)\n### (\w+)\n((?:- .+\n?)+)/);
  const latest = match
    ? { version: match[1], date: match[2], category: match[3], bullets: match[4].trim().split("\n") }
    : null;
  if (json) {
    process.stdout.write(JSON.stringify({ ok: true, version, latest }) + "\n");
  } else {
    process.stdout.write(`VERSION: ${version}\n`);
    if (latest) {
      process.stdout.write(`Latest entry: [${latest.version}] ${latest.date} (${latest.category})\n`);
      latest.bullets.forEach((bullet) => process.stdout.write(`  ${bullet}\n`));
    } else {
      process.stdout.write("No CHANGELOG.md entries yet.\n");
    }
  }
}

async function runWrite() {
  const bumpKind = arg("bump");
  const category = arg("category");
  const summary = arg("summary");
  const details = allArgs("detail").filter(Boolean);
  const filesArg = arg("files");
  const files = filesArg ? filesArg.split(",").map((item) => item.trim()).filter(Boolean) : [];

  if (!bumpKind || !["patch", "minor", "major"].includes(bumpKind)) {
    return fail('--bump must be one of "patch", "minor", "major"');
  }
  if (!category || !["Added", "Changed", "Fixed", "Removed"].includes(category)) {
    return fail('--category must be one of "Added", "Changed", "Fixed", "Removed"');
  }
  if (!summary) return fail("--summary is required (one short line describing the improvement)");

  const current = await readVersion();
  const next = bump(current, bumpKind);
  const entry = buildEntry({ version: next, category, summary, details, files });
  const existingChangelog = await readChangelog();
  const updatedChangelog = insertEntry(existingChangelog, entry);

  await fsp.writeFile(versionPath, `${next}\n`);
  await fsp.writeFile(changelogPath, updatedChangelog);

  if (json) {
    process.stdout.write(JSON.stringify({ ok: true, previousVersion: current, version: next }) + "\n");
  } else {
    process.stdout.write(`VERSION ${current} -> ${next}\n`);
    process.stdout.write(`CHANGELOG.md updated:\n\n${entry}`);
  }
}

async function main() {
  if (process.argv.includes("--check")) {
    await runCheck();
    return;
  }
  await runWrite();
}

main().catch((error) => fail(error.message));
