#!/usr/bin/env node
import { runWorkflow } from "./runtime/entry.mts";
import { runDirect } from "./runtime/cli.mts";
/* Read-only validation for the project-specific artifacts generated by /setup. */

import * as skillVendors from "./skill-vendors.mts";
import * as entryImport from "./entry-import.mts";
import type { RuntimeDeps } from "./runtime/types.mts";

type Status = "pass" | "info" | "warn" | "fail";
interface CheckResult { status: Status; name: string; detail: string }
interface CursorReport { created: string[]; differs: string[]; current: number }
interface ClaudeEntry { kind: string; detail?: string; content: string }

/** The CommonJS helpers this script needs; injectable so tests need no real project tree. */
export interface ValidatorLibs {
  cursorMirrors(root: string): CursorReport;
  resolveClaudeEntry(root: string, own: string): Promise<ClaudeEntry>;
  effectiveEntryText(root: string, file: string): Promise<{ content: string }>;
}

const defaultLibs: ValidatorLibs = {
  cursorMirrors: (skillVendors as ValidatorLibs).cursorMirrors,
  resolveClaudeEntry: (entryImport as ValidatorLibs).resolveClaudeEntry,
  effectiveEntryText: (entryImport as ValidatorLibs).effectiveEntryText,
};

const palette: Record<string, string> = { pass: "\u001b[32m", info: "\u001b[34m", warn: "\u001b[33m", fail: "\u001b[31m", heading: "\u001b[35m", reset: "\u001b[0m" };

// Runs under plain `node -e` (CommonJS): parses a TypeScript file by stripping types; exits 1 with the parser message on a syntax error.
const NODE_PARSE_SCRIPT = 'const m=require("module"),fs=require("fs");if(typeof m.stripTypeScriptTypes!=="function")process.exit(3);m.stripTypeScriptTypes(fs.readFileSync(process.argv[1],"utf8"));';
const TS_DIRS = ["ai-framework/scripts", "ai-framework/scripts/runtime", "ai-framework/hooks/scripts", ".claude/hooks", ".opencode/plugins"];

function makeValidator(argv: string[], deps: RuntimeDeps, libs: ValidatorLibs) {
  const root = deps.proc.cwd();
  const json = argv.includes("--json");
  const color = !json && !argv.includes("--no-color") && !deps.proc.env.NO_COLOR;
  const results: CheckResult[] = [];
  const out = (text: string): void => { deps.io.stdout.write(text); };

  const absolute = (relativePath: string): string => deps.path.join(root, relativePath);
  const paint = (status: string, text: string): string => (color ? `${palette[status] || ""}${text}${palette.reset}` : text);
  function record(status: Status, name: string, detail: string): void {
    results.push({ status, name, detail });
    if (!json) out(`${paint(status, status.toUpperCase().padEnd(5))} ${name}: ${detail}\n`);
  }
  // The Bun adapter's exists() is false for directories (Bun.file().exists()), so fall back to readdir.
  const exists = async (relativePath: string): Promise<boolean> =>
    (await deps.fs.exists(absolute(relativePath))) || deps.fs.readdir(absolute(relativePath)).then(() => true, () => false);
  async function requireFile(relativePath: string): Promise<boolean> {
    if (await exists(relativePath)) { record("pass", relativePath, "present"); return true; }
    record("fail", relativePath, "missing");
    return false;
  }
  // A spawn failure (missing binary) is reported like a non-zero exit, as before.
  async function run(command: string, args: string[]): Promise<{ code: number | null; stdout: string; stderr: string }> {
    try {
      const result = await (command === deps.proc.execPath ? runWorkflow(deps, args, { cwd: root, timeoutMs: 30000 }) : deps.child.run(command, args, { cwd: root, timeoutMs: 30000 }));
      return { code: result.status, stdout: result.stdout, stderr: result.stderr };
    } catch { return { code: null, stdout: "", stderr: "" }; }
  }
  const errorText = (error: unknown): string => (error instanceof Error ? error.message : String(error));

  async function checkContext(): Promise<void> {
    await Promise.all(["product.md", "architecture.md", "stack.md"].map(async (file) => {
      const relativePath = `.project/context/${file}`;
      if (!(await requireFile(relativePath))) return;
      const content = await deps.fs.readFile(absolute(relativePath));
      // Placeholders inside code (e.g. a `<build-command>` mapping table, or `Array<string>`) are
      // documentation, not unfilled template slots — only bare <...> outside code counts.
      const prose = content.replace(/```[\s\S]*?```/g, "").replace(/`[^`\n]*`/g, "");
      const incomplete = content.trim().length < 80 || /_Detecting\.\.\.|_Scanning project\.\.\.|<[^>]+>/.test(prose);
      record(incomplete ? "fail" : "pass", relativePath, incomplete ? "appears to be an unfilled setup draft" : "contains generated project context");
    }));
  }
  async function checkEntryFiles(): Promise<void> {
    if (await requireFile("AGENTS.md")) {
      const content = await deps.fs.readFile(absolute("AGENTS.md"));
      const complete = /^## Project specifics$/m.test(content) && !/Fill this in during Step 4/.test(content);
      record(complete ? "pass" : "fail", "AGENTS.md", complete ? "project specifics are filled" : "project specifics are still a setup placeholder");
    }
    if (await requireFile("CLAUDE.md")) {
      const own = await deps.fs.readFile(absolute("CLAUDE.md"));
      // A third valid shape: CLAUDE.md loads AGENTS.md through Claude Code's native `@AGENTS.md`
      // import. Validate the effective text (CLAUDE.md + its local, regular-file target); a
      // malformed, foreign, symlinked or missing target fails rather than passing on the pointer.
      const entry = await libs.resolveClaudeEntry(root, own);
      if (entry.kind === "invalid") { record("fail", "CLAUDE.md", entry.detail ?? ""); return; }
      const content = entry.content;
      const isBootstrapStub = /Bootstrap file shipped/.test(own);
      // SETUP.md has two valid completion shapes for CLAUDE.md, not one: a full mirror (no
      // pre-existing CLAUDE.md, so setup replaces the bootstrap wholesale — "## Project
      // specifics" heading present) OR an append-only merge (a real, pre-existing CLAUDE.md
      // predated this bundle, so setup preserves it and appends an "## AI Workflow" pointer
      // section instead of overwriting human-authored content). Either is complete; only the
      // untouched bootstrap stub is not.
      const isFullMirror = /^## Project specifics$/m.test(content);
      const isAppendedMerge = /^## AI Workflow \(ai-workflow-portable\)$/m.test(content);
      const complete = !isBootstrapStub && (isFullMirror || isAppendedMerge);
      record(
        complete ? "pass" : "fail",
        "CLAUDE.md",
        complete
          ? entry.kind === "import"
            ? "loads the complete AGENTS.md through @AGENTS.md"
            : isFullMirror
            ? "full project mirror is present"
            : "pre-existing CLAUDE.md preserved with an appended AI Workflow section"
          : "bootstrap file was not replaced or merged by setup",
      );
    }
  }
  // Warn, not fail: a target project's own pre-existing entry file may legitimately predate this.
  async function checkCavemanEntryFiles(): Promise<void> {
    for (const file of ["AGENTS.md", "CLAUDE.md"]) {
      if (!(await exists(file))) continue;
      const has = /^## Response style \(caveman mode\)$/m.test((await libs.effectiveEntryText(root, file)).content);
      record(has ? "pass" : "warn", file, has ? "carries the caveman response-style section" : "no caveman response-style section: the main session agent will not apply caveman mode (copy the section from the bundle's AGENTS.md)");
    }
  }
  async function checkKnowledgeGraph(): Promise<void> {
    const files = ["graphify-out/graph.json", ".project/knowledge/index.md", ".graphifyignore"];
    if (!(await Promise.all(files.map(exists))).every(Boolean)) { await Promise.all(files.map(requireFile)); return; }
    const result = await run(deps.proc.execPath, ["--experimental-strip-types", "--disable-warning=ExperimentalWarning", "ai-framework/scripts/graphify.mts", "--check", "--json"]);
    if (result.code !== 0) { record("fail", "Knowledge graph", result.stderr.trim() || "graphify reported invalid entries"); return; }
    try {
      const report = JSON.parse(result.stdout) as { problems?: { level: string }[]; stats: { total: number } };
      const errors = report.problems?.filter((problem) => problem.level === "error") ?? [];
      record(errors.length === 0 ? "pass" : "fail", "Knowledge graph", errors.length === 0 ? `graphify validated ${report.stats.total} entry(ies)` : `graphify found ${errors.length} error(s)`);
    } catch { record("fail", "Knowledge graph", "graphify did not return JSON"); }
  }
  async function checkScaffold(): Promise<void> {
    await Promise.all([".project/status.md", ".project/pitches/_followups.md", ".project/pitches/_archive/.gitkeep", ".project/pitches/_parked/.gitkeep", ".project/done-work.md"].map(requireFile));
    if (await exists(".project/status.md")) {
      const content = await deps.fs.readFile(absolute(".project/status.md"));
      const lines = content.trimEnd() === "" ? 0 : content.trimEnd().split("\n").length;
      record(lines <= 100 ? "pass" : "fail", ".project/status.md", lines <= 100 ? `${lines} lines within the 100-line limit` : `${lines} lines exceeds the 100-line limit`);
    }
    try {
      const rules = (await deps.fs.readdir(absolute(".project/rules"))).filter((name) => name.endsWith(".md"));
      record("info", ".project/rules", rules.length > 0 ? `${rules.length} stack-specific companion rule(s) generated` : "no stack-specific rules generated; valid when none apply");
    } catch { record("fail", ".project/rules", "missing"); }
  }
  // Every canonical skill and agent needs a Cursor copy; registry-managed skills carry their own
  // Cursor adapter and are validated by the doctor instead.
  function checkCursorMirrors(): void {
    let report: CursorReport;
    try { report = libs.cursorMirrors(root); } catch (error) { record("fail", ".cursor", errorText(error)); return; }
    for (const file of report.created) record("fail", file, "missing Cursor mirror; run node ai-framework/scripts/skill-vendors.mts cursor-mirrors --apply");
    for (const file of report.differs) record("warn", file, "differs from its canonical .claude file; refresh it unless the difference is a deliberate local customization");
    if (!report.created.length) record("pass", ".cursor", `${report.current + report.differs.length} canonical skill/agent mirror file(s) present`);
  }
  async function checkWorkflowDoctor(): Promise<void> {
    const result = await run(deps.proc.execPath, ["--experimental-strip-types", "--disable-warning=ExperimentalWarning", "ai-framework/scripts/workflow-doctor.mts", "--json"]);
    if (result.code !== 0) { record("fail", "Workflow doctor", result.stderr.trim() || "workflow doctor found a blocking issue"); return; }
    try {
      const report = JSON.parse(result.stdout) as { failures: number };
      record(report.failures === 0 ? "pass" : "fail", "Workflow doctor", report.failures === 0 ? "portable workflow contracts passed" : `${report.failures} workflow contract failure(s)`);
    } catch { record("fail", "Workflow doctor", "did not return JSON"); }
  }
  // K3: TypeScript entries (.mts) cannot go through `node --check`, so each one that exists is parsed
  // by stripping its types (Bun: transpile only). Silent when a project has none (pre-migration installs).
  async function checkTypeScriptEntries(): Promise<void> {
    const files: string[] = [];
    for (const dir of TS_DIRS) {
      let names: string[];
      try { names = await deps.fs.readdir(absolute(dir)); } catch { continue; }
      for (const name of names.filter((entry) => /\.(mts|ts)$/.test(entry)).sort()) files.push(`${dir}/${name}`);
    }
    if (files.length === 0) return;
    const bun = deps.runtime === "bun";
    const outcomes = await Promise.all(files.map(async (file) => {
      const args = bun ? ["build", "--no-bundle", file] : ["--experimental-strip-types", "--disable-warning=ExperimentalWarning", "-e", NODE_PARSE_SCRIPT, absolute(file)];
      return { file, result: await run(deps.proc.execPath, args) };
    }));
    const unparsed = outcomes.filter((outcome) => !bun && outcome.result.code === 3);
    if (unparsed.length > 0) record("info", "TypeScript entries", `${unparsed.length} file(s) not parse-checked: this Node has no module.stripTypeScriptTypes`);
    const bad = outcomes.filter((outcome) => outcome.result.code !== 0 && !unparsed.includes(outcome));
    if (bad.length === 0) { record("pass", "TypeScript entries", `${files.length} TypeScript file(s) parse`); return; }
    for (const { file, result } of bad) record("fail", file, `does not parse: ${result.stderr.trim().split("\n")[0] || "TypeScript check failed"}`);
  }
  async function validate(): Promise<void> {
    if (!(await exists(".project"))) { record("fail", ".project", "missing; setup has not completed"); return; }
    await Promise.all([checkWorkflowDoctor(), checkContext(), checkEntryFiles(), checkCavemanEntryFiles(), checkKnowledgeGraph(), checkScaffold(), checkCursorMirrors(), checkTypeScriptEntries()]);
  }
  return { results, json, paint, out, validate };
}

export async function main(argv: string[], deps: RuntimeDeps, libs: ValidatorLibs = defaultLibs): Promise<number> {
  try {
    const { results, json, paint, out, validate } = makeValidator(argv, deps, libs);
    if (!json) out(`${paint("heading", "Setup validator: checking generated setup artifacts concurrently...\n")}`);
    await validate();
    const failures = results.filter((result) => result.status === "fail");
    if (json) {
      out(`${JSON.stringify({ results, failures: failures.length }, null, 2)}\n`);
    } else if (failures.length > 0) {
      out(`\n${paint("fail", `Setup status: INCOMPLETE (${failures.length} issue(s))`)}\n`);
      out("Next: re-run /setup and approve the missing generated artifacts. Do not hand-write generated context, graph, or entry-file content.\n");
    } else {
      out(`\n${paint("pass", "Setup status: READY")}\nGenerated setup artifacts and portable workflow contracts passed.\n`);
    }
    if (!json) out(`Validated ${results.filter((result) => result.status === "pass").length} checks. Use --json for automation or --no-color for plain text.\n`);
    return failures.length > 0 ? 1 : 0;
  } catch (error) {
    const err = error instanceof Error ? error : new Error(String(error));
    deps.io.stderr.write(`Setup validator failed unexpectedly: ${err.stack || err.message}\n`);
    return 2;
  }
}

runDirect(import.meta.url, main);
